### ISSUE TITLE
Add support for console.log colors

### ISSUE THREAD

**Issue by nathanchase** [unjs/h3#151] opened 2022-07-23 14:55 UTC
I'd like to be able to customize the color of the console logging output.

My code:
```js
...
await console.log(
  `✔️%c[${new Date().toLocaleTimeString()}] %cSSR-Request: %c${request}`,
  'color: gray',
  'color: orange',
  'color: white',
);
...
await console.log(
  `✔️%c[${new Date().toLocaleTimeString()}] %cSSR-Response: ${response.status} %c(${duration}ms)`,
  'color: gray',
  'color: orange',
  'color: white',
);
```
The result - only white:
![image](https://user-images.githubusercontent.com/5963574/180610333-6eec609e-1da3-4c6b-b746-73440efbe994.png)

**Comment by NozomuIkuta** [comment] 2022-08-06 16:57
@nathanchase 

As far as I search, there isn't any explanation about "%c" in [Node.js spec](https://nodejs.org/api/console.html), so it seems to be supported only in browsers.

Instead, you could use [`chalk` package](https://github.com/chalk/chalk) or [ANSI escape code](https://stackoverflow.com/questions/9781218/how-to-change-node-jss-console-font-color) (`chalk` is a utility wrapper for it if I remember it correctly).

Here is a sample code of standalone h3 application, which I tested in my local.

```typescript
import { createServer } from 'http'
import { createApp, defineEventHandler } from 'h3'
import chalk from 'chalk'

const app = createApp()
app.use('/', defineEventHandler(() => {
  const time = chalk.gray(`[${new Date().toLocaleTimeString()}]`)
  const status = chalk.hex('#ff8800')(`SSR-Response: 200`) // #ff8800 is orange
  const duration = chalk.white(`(1000ms)`)

  console.log(`✔️ ${time} ${status} ${duration}`)

  return 'success'
}))

createServer(app).listen(process.env.PORT || 3000)
```

If this code doesn't work in your environment where Nitro and Vite are used (I guess it's a Nuxt application?), then the root cause will be in integration of them.

**Closed** 2022-08-07 05:01 UTC

**Comment by nathanchase** [comment] 2022-08-07 12:32
@pi0  was this more of a Nitro question than h3?

**Comment by pi0** [comment] 2022-08-07 12:46
Hi @nathanchase. You can use chalk or [colorete](https://www.npmjs.com/package/colorette) for colored output in Node.js CLI as in @NozomuIkuta's example. `%c` is only supported in  Browser console. (But yes, generally this question is more related to nitro)
