### ISSUE TITLE
defineEventHandler should take multiple handlers like express 

### ISSUE THREAD

**Issue by notshekhar** [unjs/h3#139] opened 2022-06-23 22:34 UTC
Express: app.get(handler1, handler2, handler3)
Nitro should also be like: defineEventHandler(handler1, handler2, handler3)

**Comment by pi0** [comment] 2022-06-23 22:49
This is duplicate of #127 please avoid creating multiple issues.

**Closed by pi0** 2022-06-23 22:49 UTC
