### ISSUE TITLE
Reading Buffer when input is a rawBody string

### ISSUE THREAD

**Issue by dvanmali** [unjs/h3#371] opened 2023-04-06 21:04 UTC
### Environment

Issue did not exist in [v1.6.2](https://github.com/unjs/h3/releases/tag/v1.6.2)

### Reproduction

```
[request error] [unhandled] [500] The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Promise
```

### Describe the bug

When type is buffer, the buffer should parse the buffer. When type is _rawBody, use string as-is.

**Comment by chrisspiegl** [comment] 2023-04-07 09:48
Thank you for mentioning this. I saw your pull request but couldn't apply the patch. Knowing that it works with `v1.6.2`, I used `pnpm` to `override` the h3 version in my project and got things working on firebase.

The override is necessary for firebase deploy since sub dependencies will get the current version of `h3` and thus I had to kinda force it to use `v1.6.2`.

`package.json`:

```json
{ 
  "dependencies": {
    "h3": "1.6.2"
  },
  "pnpm": {
    "overrides": {
      "h3": "1.6.2"
    }
  }
}
```

**Comment by timb-103** [comment] 2023-04-11 05:23
Having the same issue, @chrisspiegl solution worked.

**Comment by brunomoyse** [comment] 2023-04-14 13:05
same problem, thank you @chrisspiegl for the work around waiting for the merge

**Comment by pi0** [comment] 2023-06-20 21:34
HI. This should have been fixed in latest h3 releases. Please let me know to investigate if you can still reproduce.

**Closed by pi0** 2023-06-20 21:34 UTC

**Comment by pi0** [comment] 2024-01-03 00:41
Another related fix for form-data requests (firebase parses them as json in `req.body`): https://github.com/unjs/h3/pull/604
