### ISSUE TITLE
Adding an authorization header to the request in server middleware

### ISSUE THREAD

**Issue by Birleyici** [unjs/h3#565] opened 2023-10-30 07:13 UTC
### Describe the feature

I'm using h3 built into nuxt. I need to be able to set a header to add a bearer token to the request in the server middleware.I tried every way but I couldn't succeed. How can I do this in the block below?

server/middleware/addBearerToken.js
```

export default fromNodeMiddleware((req, res, next) => {

  
    const token = 'TOKEN'
    
      // ---HERE---
      //How can I set my token to the headers ?
      
    next();
});
```

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by peterroe** [comment] 2023-10-30 17:16
Hi, Maybe you can do like this:
```ts
fromNodeMiddleware((req, res, next) => {
    req.setHeader("token", "token");
    next();
}),
```

**Comment by Birleyici** [comment] 2023-10-31 05:47
> ```ts
>     req.setHeader("token", "token");
> ```

I tried this before and I encounter the following error.
`500
req.setHeader is not a function

at null. (C:\Users\HP\Desktop\BeyrahaV2\server\middleware\deneme.js:2:1)
at /C:/Users/HP/Desktop/BeyrahaV2/node_modules/h3/dist/index.mjs:1876:24
at new Promise ()
at callNodeListener (/C:/Users/HP/Desktop/BeyrahaV2/node_modules/h3/dist/index.mjs:1867:10)
at Object.handler (/C:/Users/HP/Desktop/BeyrahaV2/node_modules/h3/dist/index.mjs:1829:12)
at Object.handler (/C:/Users/HP/Desktop/BeyrahaV2/node_modules/h3/dist/index.mjs:1630:31)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async toNodeHandle (/C:/Users/HP/Desktop/BeyrahaV2/node_modules/h3/dist/index.mjs:1840:7)
at async ufetch (/C:/Users/HP/Desktop/BeyrahaV2/node_modules/unenv/runtime/fetch/index.mjs:9:17)
at null.errorhandler (C:\Users\HP\Desktop\BeyrahaV2\node_modules\nuxt\dist\core\runtime\nitro\error.js:35:30)`

server middleware file:

`export default fromNodeMiddleware((req, res, next) => {
  req.setHeader("token", "token");
  next()
})`

**Comment by platform-kit** [comment] 2023-12-23 09:23
@ceodevforce this issue shows up when you use Nuxt3/Nitro to ship to Netlify. 

`getHeader` works as expected when running locally under `node-server` preset. But not once the lambdas are built and deployed to Netlify Functions/lambda.

Obviously, headers, especially `authorization` are something devs need to use. Workarounds like cookies etc won't work.

Any ideas about how to fix this?

**Comment by titan-65** [comment] 2023-12-23 12:18
Ok, I get what you are saying however, since cookies are out have you tried using the nuxt context or using the event instead of getHeader like this `const token = event.node.req.headers('Authorization') || event.node.req.headers('authorization') || getCookie(event, 'token') || h3Header(event, 'token') || h3Query(event, 'token') || h3Cookie(event, 'token')`. I took this from a package I have been working on here [j3-Jwt](https://www.npmjs.com/package/h3-jwt)

**Comment by platform-kit** [comment] 2023-12-23 23:51
@titan-65  `event.node.req.headers` is undefined in Netlify functions context.

**Comment by titan-65** [comment] 2023-12-25 04:59
Can you share the exact code reproduction so i can see?

**Comment by Tarabass** [comment] 2024-01-03 13:18
I coincidentally opened an issue on nuxt with almost the same feature request:

https://github.com/nuxt/nuxt/issues/24971#issue-2060790877 

My workaround is indeed setting the header on the event context of a server middleware. However, this means that the headers have to be set manually in every api event by passing through the headers object. So yes, all my headers are maintained in one place, the auth.ts middleware, but every api endpoint needs to know about it..

**Comment by manniL** [comment] 2024-02-16 10:57
Closing this based on https://github.com/nuxt/nuxt/issues/24971#issuecomment-1948167746. Similar concepts apply here 👍

**Closed by manniL** 2024-02-16 10:57 UTC
