### ISSUE TITLE
[bug] large file upload cause crashes

### ISSUE THREAD

**Issue by mihail727** [unjs/h3#103] opened 2022-04-20 15:19 UTC
i'm trying to upload file from client and save it locally on the server...
for the server side i' using busboy.... and it work correctly only with small files.... with large file i get an error:
```
 ERROR  [h3] write EPIPE                                                                                                                                     17:21:55

  at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16
```

**Comment by andrewrynhard** [comment] 2022-11-08 21:34
I am running in this exact issue. Any ideas? @mihail727 did you ever find a solution?

**Comment by pi0** [comment] 2023-07-10 17:51
Hi. Since this issue is open for long time without reproduction, i am closing it. If you can make a stable reproduction, please share.

**Closed by pi0** 2023-07-10 17:51 UTC
Labels: bug, needs reproduction
