### ISSUE TITLE
Fix type information to allow express middlewares

### ISSUE THREAD

**Issue by tobiasdiez** [unjs/h3#146] opened 2022-07-20 09:42 UTC
If you use an express-middleware (such as session or passport), one gets the following typescript error:
```
Type 'RequestHandler<ParamsDictionary, any, any, ParsedQs, Record<string, any>>' is not comparable to type 'EventHandler<any>'.
```
Example-code:
```ts
import session from 'express-session'
import passport from 'passport'
import { createApp } from 'h3'

const app = createApp()
app.use(session())
app.use(passport.initialize())
```

**Comment by NozomuIkuta** [comment] 2022-08-04 14:51
@tobiasdiez 

@pi0 explains it in #73 why they are changing middleware signature.

In my understanding, h3 is aiming to be environment-agnostic server framework for future, even with trade-offs like abandoning the existing ecosystem.

One possible compromise might be to provide a _glue_ function that convert `event` from `req/res` and vice versa, so that we can wrap legacy middlewares, as well as letting the community recreate h3-dedicated middlewares.

```typescript
// This is a virtual code 
// `eventify` passes `req/res` and `next` function to the wrapped middleware
app.use(eventify(session()))
```

**Comment by tobiasdiez** [comment] 2022-08-04 15:25
Sorry, I should have been more precise. There is already such a wrapper in place (und the hood) and the above code does work. It's only that TypeScript is throwing an error, so I guess something is off here https://github.com/unjs/h3/blob/4b83bdf83b94da3f66018378d39c5cc24afdf43f/src/types.ts#L23

**Comment by NozomuIkuta** [comment] 2022-08-05 18:04
Sorry, I misunderstand you.

By the way, I couldn't instantly reproduce the error that you are taking about.
Would you provide a link to reproduction, so that I can investigate it more deeply?

**Comment by tobiasdiez** [comment] 2022-08-31 21:44
@NozomuIkuta please have look at this ts [Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAZwKYIcCA7OAzKERwDkSAHmFCggLTKroaEBQokscYAhqq-LvkZ27QYTFsLgBvOAGMKHGEgCCYMHAC+OPAUIALAMxNG0zAngcVcALwy5C5WAAUASkbmwAOgCuyB7TSZnFzcvH0EEHndgDGAYYA4AG2AALyRAoA). The `app.use` calls are showing ts errors.

**Comment by NozomuIkuta** [comment] 2022-09-15 19:04
@tobiasdiez 

For your information, I found that @pi0 had created [a branch where he is removing compatibility with legacy Express-style middleware](https://github.com/unjs/h3/tree/c04c44b760a8e14f6db03a6a1bdfa5f4e47419f7) whose signature is `(req, res, next?) => {}`. 

---

By the way, it's written in README that:

> For maximum compatibility with connect/express middleware (`req, res, next?` signature), h3 converts classic middleware into a promisified version ready to use with stack runner:

Once the branch is merged, the "maximum" compatibility get to be "zero" (note: this change has been planned in #73).

So, at this moment, all options we have would be (1) to make up h3-native auth solution by ourselves rather than making h3 complex by adding Express middleware support, or (2) to give a support to authors so that they can do it for us (e.g. sponsoring via GitHub). That's just because h3 is an OSS.

**Comment by pi0** [comment] 2022-10-18 09:38
Middleware made for express, depend on specific auegmentations coming from express app itself (.json(), .cookie(), etc)

In order to use express middleware with h3, you need to first create an express app:

```ts
const app = h3.createApp()

const expressApp = express()
expressApp.use(expressMiddleware()

app.use(h3.fromNodeMiddleware(expressApp))
```

**Closed by pi0** 2022-10-18 09:38 UTC
